/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AAtributoFator extends PFator
{
    private PAtributo _atributo_;

    public AAtributoFator()
    {
        // Constructor
    }

    public AAtributoFator(
        @SuppressWarnings("hiding") PAtributo _atributo_)
    {
        // Constructor
        setAtributo(_atributo_);

    }

    @Override
    public Object clone()
    {
        return new AAtributoFator(
            cloneNode(this._atributo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributoFator(this);
    }

    public PAtributo getAtributo()
    {
        return this._atributo_;
    }

    public void setAtributo(PAtributo node)
    {
        if(this._atributo_ != null)
        {
            this._atributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atributo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atributo_ == child)
        {
            this._atributo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atributo_ == oldChild)
        {
            setAtributo((PAtributo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
