/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ABoolFator extends PFator
{
    private PExpBool _expBool_;

    public ABoolFator()
    {
        // Constructor
    }

    public ABoolFator(
        @SuppressWarnings("hiding") PExpBool _expBool_)
    {
        // Constructor
        setExpBool(_expBool_);

    }

    @Override
    public Object clone()
    {
        return new ABoolFator(
            cloneNode(this._expBool_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolFator(this);
    }

    public PExpBool getExpBool()
    {
        return this._expBool_;
    }

    public void setExpBool(PExpBool node)
    {
        if(this._expBool_ != null)
        {
            this._expBool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBool_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBool_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBool_ == child)
        {
            this._expBool_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBool_ == oldChild)
        {
            setExpBool((PExpBool) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
