/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoDecFuncao extends PDecFuncao
{
    private TDoisMaior _doisMaior_;
    private TFuncao _funcao_;
    private TDoisPontos _doisPontos_;
    private PTipo _tipo_;
    private TId _id_;
    private TParEsq _fe_;
    private PParametros _parametros_;
    private TParDir _fd_;
    private PBloco _bloco_;

    public ADecFuncaoDecFuncao()
    {
        // Constructor
    }

    public ADecFuncaoDecFuncao(
        @SuppressWarnings("hiding") TDoisMaior _doisMaior_,
        @SuppressWarnings("hiding") TFuncao _funcao_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TParEsq _fe_,
        @SuppressWarnings("hiding") PParametros _parametros_,
        @SuppressWarnings("hiding") TParDir _fd_,
        @SuppressWarnings("hiding") PBloco _bloco_)
    {
        // Constructor
        setDoisMaior(_doisMaior_);

        setFuncao(_funcao_);

        setDoisPontos(_doisPontos_);

        setTipo(_tipo_);

        setId(_id_);

        setFe(_fe_);

        setParametros(_parametros_);

        setFd(_fd_);

        setBloco(_bloco_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoDecFuncao(
            cloneNode(this._doisMaior_),
            cloneNode(this._funcao_),
            cloneNode(this._doisPontos_),
            cloneNode(this._tipo_),
            cloneNode(this._id_),
            cloneNode(this._fe_),
            cloneNode(this._parametros_),
            cloneNode(this._fd_),
            cloneNode(this._bloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoDecFuncao(this);
    }

    public TDoisMaior getDoisMaior()
    {
        return this._doisMaior_;
    }

    public void setDoisMaior(TDoisMaior node)
    {
        if(this._doisMaior_ != null)
        {
            this._doisMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisMaior_ = node;
    }

    public TFuncao getFuncao()
    {
        return this._funcao_;
    }

    public void setFuncao(TFuncao node)
    {
        if(this._funcao_ != null)
        {
            this._funcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcao_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TParEsq getFe()
    {
        return this._fe_;
    }

    public void setFe(TParEsq node)
    {
        if(this._fe_ != null)
        {
            this._fe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fe_ = node;
    }

    public PParametros getParametros()
    {
        return this._parametros_;
    }

    public void setParametros(PParametros node)
    {
        if(this._parametros_ != null)
        {
            this._parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametros_ = node;
    }

    public TParDir getFd()
    {
        return this._fd_;
    }

    public void setFd(TParDir node)
    {
        if(this._fd_ != null)
        {
            this._fd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fd_ = node;
    }

    public PBloco getBloco()
    {
        return this._bloco_;
    }

    public void setBloco(PBloco node)
    {
        if(this._bloco_ != null)
        {
            this._bloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._doisMaior_)
            + toString(this._funcao_)
            + toString(this._doisPontos_)
            + toString(this._tipo_)
            + toString(this._id_)
            + toString(this._fe_)
            + toString(this._parametros_)
            + toString(this._fd_)
            + toString(this._bloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._doisMaior_ == child)
        {
            this._doisMaior_ = null;
            return;
        }

        if(this._funcao_ == child)
        {
            this._funcao_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._fe_ == child)
        {
            this._fe_ = null;
            return;
        }

        if(this._parametros_ == child)
        {
            this._parametros_ = null;
            return;
        }

        if(this._fd_ == child)
        {
            this._fd_ = null;
            return;
        }

        if(this._bloco_ == child)
        {
            this._bloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._doisMaior_ == oldChild)
        {
            setDoisMaior((TDoisMaior) newChild);
            return;
        }

        if(this._funcao_ == oldChild)
        {
            setFuncao((TFuncao) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._fe_ == oldChild)
        {
            setFe((TParEsq) newChild);
            return;
        }

        if(this._parametros_ == oldChild)
        {
            setParametros((PParametros) newChild);
            return;
        }

        if(this._fd_ == oldChild)
        {
            setFd((TParDir) newChild);
            return;
        }

        if(this._bloco_ == oldChild)
        {
            setBloco((PBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
