/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ADecObjDecObj extends PDecObj
{
    private TObjeto _objeto_;
    private TDoisPontos _doisPontos_;
    private PTipoMolde _tipoMolde_;
    private TId _id_;
    private TPontoVirgula _pontoVirgula_;

    public ADecObjDecObj()
    {
        // Constructor
    }

    public ADecObjDecObj(
        @SuppressWarnings("hiding") TObjeto _objeto_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_,
        @SuppressWarnings("hiding") PTipoMolde _tipoMolde_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setObjeto(_objeto_);

        setDoisPontos(_doisPontos_);

        setTipoMolde(_tipoMolde_);

        setId(_id_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ADecObjDecObj(
            cloneNode(this._objeto_),
            cloneNode(this._doisPontos_),
            cloneNode(this._tipoMolde_),
            cloneNode(this._id_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObjDecObj(this);
    }

    public TObjeto getObjeto()
    {
        return this._objeto_;
    }

    public void setObjeto(TObjeto node)
    {
        if(this._objeto_ != null)
        {
            this._objeto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objeto_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    public PTipoMolde getTipoMolde()
    {
        return this._tipoMolde_;
    }

    public void setTipoMolde(PTipoMolde node)
    {
        if(this._tipoMolde_ != null)
        {
            this._tipoMolde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoMolde_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objeto_)
            + toString(this._doisPontos_)
            + toString(this._tipoMolde_)
            + toString(this._id_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objeto_ == child)
        {
            this._objeto_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        if(this._tipoMolde_ == child)
        {
            this._tipoMolde_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objeto_ == oldChild)
        {
            setObjeto((TObjeto) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        if(this._tipoMolde_ == oldChild)
        {
            setTipoMolde((PTipoMolde) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
