/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ADefinicaoConteudoBloco extends PConteudoBloco
{
    private PDefinicao _definicao_;

    public ADefinicaoConteudoBloco()
    {
        // Constructor
    }

    public ADefinicaoConteudoBloco(
        @SuppressWarnings("hiding") PDefinicao _definicao_)
    {
        // Constructor
        setDefinicao(_definicao_);

    }

    @Override
    public Object clone()
    {
        return new ADefinicaoConteudoBloco(
            cloneNode(this._definicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefinicaoConteudoBloco(this);
    }

    public PDefinicao getDefinicao()
    {
        return this._definicao_;
    }

    public void setDefinicao(PDefinicao node)
    {
        if(this._definicao_ != null)
        {
            this._definicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicao_ == child)
        {
            this._definicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicao_ == oldChild)
        {
            setDefinicao((PDefinicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
