/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ADefMoldeDefMolde extends PDefMolde
{
    private TMolde _molde_;
    private TIdMolde _idMolde_;
    private TContem _contem_;
    private PAtributos _atributos_;
    private PMetodos _metodos_;
    private TFim _fim_;

    public ADefMoldeDefMolde()
    {
        // Constructor
    }

    public ADefMoldeDefMolde(
        @SuppressWarnings("hiding") TMolde _molde_,
        @SuppressWarnings("hiding") TIdMolde _idMolde_,
        @SuppressWarnings("hiding") TContem _contem_,
        @SuppressWarnings("hiding") PAtributos _atributos_,
        @SuppressWarnings("hiding") PMetodos _metodos_,
        @SuppressWarnings("hiding") TFim _fim_)
    {
        // Constructor
        setMolde(_molde_);

        setIdMolde(_idMolde_);

        setContem(_contem_);

        setAtributos(_atributos_);

        setMetodos(_metodos_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new ADefMoldeDefMolde(
            cloneNode(this._molde_),
            cloneNode(this._idMolde_),
            cloneNode(this._contem_),
            cloneNode(this._atributos_),
            cloneNode(this._metodos_),
            cloneNode(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefMoldeDefMolde(this);
    }

    public TMolde getMolde()
    {
        return this._molde_;
    }

    public void setMolde(TMolde node)
    {
        if(this._molde_ != null)
        {
            this._molde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._molde_ = node;
    }

    public TIdMolde getIdMolde()
    {
        return this._idMolde_;
    }

    public void setIdMolde(TIdMolde node)
    {
        if(this._idMolde_ != null)
        {
            this._idMolde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idMolde_ = node;
    }

    public TContem getContem()
    {
        return this._contem_;
    }

    public void setContem(TContem node)
    {
        if(this._contem_ != null)
        {
            this._contem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contem_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    public PMetodos getMetodos()
    {
        return this._metodos_;
    }

    public void setMetodos(PMetodos node)
    {
        if(this._metodos_ != null)
        {
            this._metodos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metodos_ = node;
    }

    public TFim getFim()
    {
        return this._fim_;
    }

    public void setFim(TFim node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._molde_)
            + toString(this._idMolde_)
            + toString(this._contem_)
            + toString(this._atributos_)
            + toString(this._metodos_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._molde_ == child)
        {
            this._molde_ = null;
            return;
        }

        if(this._idMolde_ == child)
        {
            this._idMolde_ = null;
            return;
        }

        if(this._contem_ == child)
        {
            this._contem_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        if(this._metodos_ == child)
        {
            this._metodos_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._molde_ == oldChild)
        {
            setMolde((TMolde) newChild);
            return;
        }

        if(this._idMolde_ == oldChild)
        {
            setIdMolde((TIdMolde) newChild);
            return;
        }

        if(this._contem_ == oldChild)
        {
            setContem((TContem) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        if(this._metodos_ == oldChild)
        {
            setMetodos((PMetodos) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TFim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
