/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AInstanciaFator extends PFator
{
    private PInstancia _instancia_;

    public AInstanciaFator()
    {
        // Constructor
    }

    public AInstanciaFator(
        @SuppressWarnings("hiding") PInstancia _instancia_)
    {
        // Constructor
        setInstancia(_instancia_);

    }

    @Override
    public Object clone()
    {
        return new AInstanciaFator(
            cloneNode(this._instancia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstanciaFator(this);
    }

    public PInstancia getInstancia()
    {
        return this._instancia_;
    }

    public void setInstancia(PInstancia node)
    {
        if(this._instancia_ != null)
        {
            this._instancia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instancia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instancia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instancia_ == child)
        {
            this._instancia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instancia_ == oldChild)
        {
            setInstancia((PInstancia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
