/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ANumerosTermo extends PTermo
{
    private TNumeros _numeros_;

    public ANumerosTermo()
    {
        // Constructor
    }

    public ANumerosTermo(
        @SuppressWarnings("hiding") TNumeros _numeros_)
    {
        // Constructor
        setNumeros(_numeros_);

    }

    @Override
    public Object clone()
    {
        return new ANumerosTermo(
            cloneNode(this._numeros_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumerosTermo(this);
    }

    public TNumeros getNumeros()
    {
        return this._numeros_;
    }

    public void setNumeros(TNumeros node)
    {
        if(this._numeros_ != null)
        {
            this._numeros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeros_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeros_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeros_ == child)
        {
            this._numeros_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeros_ == oldChild)
        {
            setNumeros((TNumeros) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
