/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosParametros extends PParametros
{
    private PParametro _parametro_;
    private final LinkedList<PMaisParametro> _maisParametro_ = new LinkedList<PMaisParametro>();

    public AParametrosParametros()
    {
        // Constructor
    }

    public AParametrosParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _maisParametro_)
    {
        // Constructor
        setParametro(_parametro_);

        setMaisParametro(_maisParametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosParametros(
            cloneNode(this._parametro_),
            cloneList(this._maisParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PMaisParametro> getMaisParametro()
    {
        return this._maisParametro_;
    }

    public void setMaisParametro(List<?> list)
    {
        for(PMaisParametro e : this._maisParametro_)
        {
            e.parent(null);
        }
        this._maisParametro_.clear();

        for(Object obj_e : list)
        {
            PMaisParametro e = (PMaisParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._maisParametro_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._maisParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._maisParametro_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PMaisParametro> i = this._maisParametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMaisParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
