/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAssinaturaParametrosAssinatura extends PParametrosAssinatura
{
    private PParametroAssinatura _parametroAssinatura_;
    private final LinkedList<PMaisParametrosAssinatura> _maisParametrosAssinatura_ = new LinkedList<PMaisParametrosAssinatura>();

    public AParametrosAssinaturaParametrosAssinatura()
    {
        // Constructor
    }

    public AParametrosAssinaturaParametrosAssinatura(
        @SuppressWarnings("hiding") PParametroAssinatura _parametroAssinatura_,
        @SuppressWarnings("hiding") List<?> _maisParametrosAssinatura_)
    {
        // Constructor
        setParametroAssinatura(_parametroAssinatura_);

        setMaisParametrosAssinatura(_maisParametrosAssinatura_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAssinaturaParametrosAssinatura(
            cloneNode(this._parametroAssinatura_),
            cloneList(this._maisParametrosAssinatura_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAssinaturaParametrosAssinatura(this);
    }

    public PParametroAssinatura getParametroAssinatura()
    {
        return this._parametroAssinatura_;
    }

    public void setParametroAssinatura(PParametroAssinatura node)
    {
        if(this._parametroAssinatura_ != null)
        {
            this._parametroAssinatura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametroAssinatura_ = node;
    }

    public LinkedList<PMaisParametrosAssinatura> getMaisParametrosAssinatura()
    {
        return this._maisParametrosAssinatura_;
    }

    public void setMaisParametrosAssinatura(List<?> list)
    {
        for(PMaisParametrosAssinatura e : this._maisParametrosAssinatura_)
        {
            e.parent(null);
        }
        this._maisParametrosAssinatura_.clear();

        for(Object obj_e : list)
        {
            PMaisParametrosAssinatura e = (PMaisParametrosAssinatura) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._maisParametrosAssinatura_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametroAssinatura_)
            + toString(this._maisParametrosAssinatura_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametroAssinatura_ == child)
        {
            this._parametroAssinatura_ = null;
            return;
        }

        if(this._maisParametrosAssinatura_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametroAssinatura_ == oldChild)
        {
            setParametroAssinatura((PParametroAssinatura) newChild);
            return;
        }

        for(ListIterator<PMaisParametrosAssinatura> i = this._maisParametrosAssinatura_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMaisParametrosAssinatura) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
