/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AProgramaPrograma extends PPrograma
{
    private PFamilia _familia_;
    private final LinkedList<PDefMolde> _defMolde_ = new LinkedList<PDefMolde>();

    public AProgramaPrograma()
    {
        // Constructor
    }

    public AProgramaPrograma(
        @SuppressWarnings("hiding") PFamilia _familia_,
        @SuppressWarnings("hiding") List<?> _defMolde_)
    {
        // Constructor
        setFamilia(_familia_);

        setDefMolde(_defMolde_);

    }

    @Override
    public Object clone()
    {
        return new AProgramaPrograma(
            cloneNode(this._familia_),
            cloneList(this._defMolde_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramaPrograma(this);
    }

    public PFamilia getFamilia()
    {
        return this._familia_;
    }

    public void setFamilia(PFamilia node)
    {
        if(this._familia_ != null)
        {
            this._familia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._familia_ = node;
    }

    public LinkedList<PDefMolde> getDefMolde()
    {
        return this._defMolde_;
    }

    public void setDefMolde(List<?> list)
    {
        for(PDefMolde e : this._defMolde_)
        {
            e.parent(null);
        }
        this._defMolde_.clear();

        for(Object obj_e : list)
        {
            PDefMolde e = (PDefMolde) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._defMolde_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._familia_)
            + toString(this._defMolde_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._familia_ == child)
        {
            this._familia_ = null;
            return;
        }

        if(this._defMolde_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._familia_ == oldChild)
        {
            setFamilia((PFamilia) newChild);
            return;
        }

        for(ListIterator<PDefMolde> i = this._defMolde_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDefMolde) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
