/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoRelacao extends PRelacao
{
    private TMolde _molde_;
    private TIdMolde _esq_;
    private TSe _se_;
    private TPassa _passa_;
    private TPor _por_;
    private TIdMolde _dir_;

    public ARelacaoRelacao()
    {
        // Constructor
    }

    public ARelacaoRelacao(
        @SuppressWarnings("hiding") TMolde _molde_,
        @SuppressWarnings("hiding") TIdMolde _esq_,
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TPassa _passa_,
        @SuppressWarnings("hiding") TPor _por_,
        @SuppressWarnings("hiding") TIdMolde _dir_)
    {
        // Constructor
        setMolde(_molde_);

        setEsq(_esq_);

        setSe(_se_);

        setPassa(_passa_);

        setPor(_por_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoRelacao(
            cloneNode(this._molde_),
            cloneNode(this._esq_),
            cloneNode(this._se_),
            cloneNode(this._passa_),
            cloneNode(this._por_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoRelacao(this);
    }

    public TMolde getMolde()
    {
        return this._molde_;
    }

    public void setMolde(TMolde node)
    {
        if(this._molde_ != null)
        {
            this._molde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._molde_ = node;
    }

    public TIdMolde getEsq()
    {
        return this._esq_;
    }

    public void setEsq(TIdMolde node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TPassa getPassa()
    {
        return this._passa_;
    }

    public void setPassa(TPassa node)
    {
        if(this._passa_ != null)
        {
            this._passa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passa_ = node;
    }

    public TPor getPor()
    {
        return this._por_;
    }

    public void setPor(TPor node)
    {
        if(this._por_ != null)
        {
            this._por_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._por_ = node;
    }

    public TIdMolde getDir()
    {
        return this._dir_;
    }

    public void setDir(TIdMolde node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._molde_)
            + toString(this._esq_)
            + toString(this._se_)
            + toString(this._passa_)
            + toString(this._por_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._molde_ == child)
        {
            this._molde_ = null;
            return;
        }

        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._passa_ == child)
        {
            this._passa_ = null;
            return;
        }

        if(this._por_ == child)
        {
            this._por_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._molde_ == oldChild)
        {
            setMolde((TMolde) newChild);
            return;
        }

        if(this._esq_ == oldChild)
        {
            setEsq((TIdMolde) newChild);
            return;
        }

        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._passa_ == oldChild)
        {
            setPassa((TPassa) newChild);
            return;
        }

        if(this._por_ == oldChild)
        {
            setPor((TPor) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((TIdMolde) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
