/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ASeSenaoSeSenao extends PSeSenao
{
    private TSe _se_;
    private TParEsq _parEsq_;
    private PExp _primeira_;
    private TParDir _parDir_;
    private PExp _segunda_;
    private TSenao _senao_;
    private PExp _terceira_;

    public ASeSenaoSeSenao()
    {
        // Constructor
    }

    public ASeSenaoSeSenao(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExp _primeira_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PExp _segunda_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PExp _terceira_)
    {
        // Constructor
        setSe(_se_);

        setParEsq(_parEsq_);

        setPrimeira(_primeira_);

        setParDir(_parDir_);

        setSegunda(_segunda_);

        setSenao(_senao_);

        setTerceira(_terceira_);

    }

    @Override
    public Object clone()
    {
        return new ASeSenaoSeSenao(
            cloneNode(this._se_),
            cloneNode(this._parEsq_),
            cloneNode(this._primeira_),
            cloneNode(this._parDir_),
            cloneNode(this._segunda_),
            cloneNode(this._senao_),
            cloneNode(this._terceira_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeSenaoSeSenao(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExp getPrimeira()
    {
        return this._primeira_;
    }

    public void setPrimeira(PExp node)
    {
        if(this._primeira_ != null)
        {
            this._primeira_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primeira_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PExp getSegunda()
    {
        return this._segunda_;
    }

    public void setSegunda(PExp node)
    {
        if(this._segunda_ != null)
        {
            this._segunda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segunda_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PExp getTerceira()
    {
        return this._terceira_;
    }

    public void setTerceira(PExp node)
    {
        if(this._terceira_ != null)
        {
            this._terceira_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._terceira_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._parEsq_)
            + toString(this._primeira_)
            + toString(this._parDir_)
            + toString(this._segunda_)
            + toString(this._senao_)
            + toString(this._terceira_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._primeira_ == child)
        {
            this._primeira_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._segunda_ == child)
        {
            this._segunda_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._terceira_ == child)
        {
            this._terceira_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._primeira_ == oldChild)
        {
            setPrimeira((PExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._segunda_ == oldChild)
        {
            setSegunda((PExp) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._terceira_ == oldChild)
        {
            setTerceira((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
