/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TTexto extends Token
{
    public TTexto()
    {
        super.setText("Texto");
    }

    public TTexto(int line, int pos)
    {
        super.setText("Texto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTexto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTexto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTexto text.");
    }
}
