/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TNumero extends Token
{
    public TNumero()
    {
        super.setText("Numero");
    }

    public TNumero(int line, int pos)
    {
        super.setText("Numero");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumero(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumero(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumero text.");
    }
}
